### ISSUE TITLE
Error receiving request to upgrade to websocket with EngineIO

### ISSUE THREAD

**Issue by menudoproblema** [imachug/gevent-ws#2]
This is the traceback:
```
Traceback (most recent call last):
  File "/Users/menudoproblema/env/lib/python3.7/site-packages/gevent_ws/__init__.py", line 233, in handle_one_response
    self.run_application()
  File "/Users/menudoproblema/env/lib/python3.7/site-packages/gevent/pywsgi.py", line 915, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/Users/menudoproblema/env/lib/python3.7/site-packages/engineio/middleware.py", line 60, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/Users/menudoproblema/env/lib/python3.7/site-packages/socketio/server.py", line 555, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/Users/menudoproblema/env/lib/python3.7/site-packages/engineio/server.py", line 377, in handle_request
    environ, start_response)
  File "/Users/menudoproblema/env/lib/python3.7/site-packages/engineio/socket.py", line 108, in handle_get_request
    start_response)
  File "/Users/menudoproblema/env/lib/python3.7/site-packages/engineio/socket.py", line 152, in _upgrade_websocket
    return ws(environ, start_response)
  File "/Users/menudoproblema/env/lib/python3.7/site-packages/engineio/async_drivers/gevent.py", line 40, in __call__
    self.version = self._sock.version
AttributeError: 'WebSocket' object has no attribute 'version'
```

EngineIO [is expecting](https://github.com/miguelgrinberg/python-engineio/blob/e12f5176a636d3848f4b3cba364360b6f86f996b/engineio/async_drivers/gevent.py#L40) the following fields for an object of type WebSocket:
* version
* path
* origin
* protocol

Thanks!

**Comment by purplesyringa** [comment]
Thanks, I've pushed the fix as v2.0.8. Can you please make sure it works?

**Comment by menudoproblema** [comment]
```
2020-03-22 01:10:10 MacBook.local engineio.server[23861] INFO 5b0b3c421a884edc9c17433878b702cd: Upgrade to websocket successful
```
Everyting ok! Thanks!

**Comment by purplesyringa** [comment]
Great, I'm closing this issue then. Please make another one or comment here if you have any problems.
